ljsnell/BQ-Client

client/src/App.js, server/index.js
=> Session syncing

client/src/App.js
=> Added logic to account for the quiz ending.

client/src/App.js
Only lets quizmaster direct the quiz.
=> Added logic to control the quizmaster functions.

client/src/App.js
Moved jump functions to their own queue.
=> Specific sockets

client/src/App.js
Updated to only allow the first person to jump on the question.
=> Jump security

client/src/App.js
=> Multi room

client/src/App.js
Added scoreboard functionality.
=> Scoreboard

client/src/App.js
Updated with a hard coded list of quizzes.
=> Round selector

client/src/App.js
Added code to read in answer text.
=> Added answer text.

client/src/App.js
Signed-off-by: ljsnell <ljsnell7@gmail.com>
=> Updated to call the heroku endpoint.

src/App.js
Added changes based on Don and Deb's suggestions.
=> Don and Deb

src/App.js
Muting a tab via Google Chrome wasn't working so I added a programmatic solution.
=> Slightly gully solution, but it'll work.

src/App.js
Added changes based on Deb's feedback.
=> Further enhancements

src/App.js
Added Jeff's questions. And removed score board temporarily.
=> Added new questions and removed score board.

src/App.js, src/webserviceCalls.js
Moved webservice to its own class, and created more generic function for getting the next question. Credit to @sergeihanka
=> Webservice split

src/App.js
Trying to make it harder for people to get their jump superseded by a later one.
=> Fixing jump

src/App.js
Hoping this fixed the jumping issue.
=> Maybe fixed jump

src/App.js
Wasn't actually filtering by chapter.
=> Random q fix

README.md, src/webserviceCalls.js
Updated readme and added the local endpoints to the `webserviceCalls.js`. In theory I could move a lot of the local endpoints to a .env file or something of that nature, not sure if that's less work or not in the long run though.
=> Updated readme.

src/App.js
if bonus question, then read the whole questions and not just one word.
=> bonus audio fix

src/App.js, src/constants.js, src/webserviceCalls.js
all logic and ui expect the extra * information to inform that Bonus is not part of this.
=> UI for future question type

src/App.js
=> Revert "Send jump"

src/App.js, src/globals.js
This should actually work now.
=> Updated to have working light check code.

src/App.js
=> Updated with audio fix from Nadia.

src/Quiz.js, src/webserviceCalls.js
Wasn't reading from the right field, so 'Question: ' wasn't leading the question.
=> Pulling from correct field

src/Quiz.js
Updated to use the cleaned up random API. https://github.com/ljsnell/bible_quiz_questions_api/pull/18
=> Updated indexes.

src/Quiz.js
Updated so fields should all be cleaned out on next question.
=> Updated to cleanout fields on next_question_type.

src/App.css, src/Quiz.js
Now we've got 3 footer buttons. Not sure on colors.
=> 3 footer buttons

src/Quiz.js
@Nissi126 you might want to take this change in too.
=> Now bonus question gets reset to 0 on quiz number change.

src/App.css, src/Quiz.js
Updated to add a spectator mode based on the username. We'll now require chair numbers if they want to jump.
=> Spectator mode

src/Quiz.js
=> Revert "Jump fix attempt infinity"

src/Quiz.js
James is book #2 in the database.
=> Hardcoded to just James atm.
